# Generated by Django 3.1.3 on 2020-11-26 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_time', models.DateTimeField()),
                ('pick_up_place', models.CharField(max_length=80)),
                ('drop_off_place', models.CharField(max_length=80)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.driver')),
            ],
        ),
    ]
